import { useState } from "react";
import { useListProposals, useCreateProposal, useUpdateProposal, useUpdateProposalStatus, useGenerateProposal, useListLeads, useSendProposalEmail } from "@workspace/api-client-react";
import { getListProposalsQueryKey, getListLeadsQueryKey } from "@workspace/api-client-react";
import type { ProposalWithLead, Lead, SendProposalEmailResult } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { StatusBadge } from "@/components/Badge";
import { FileText, Plus, Zap, Edit2, LayoutList, Columns3, Download, Mail, X, ExternalLink } from "lucide-react";
import { cn, formatCurrency, formatDate } from "@/lib/utils";
import { pdf, Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const pdfStyles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", backgroundColor: "#ffffff" },
  header: { backgroundColor: "#1A7A45", padding: 24, borderRadius: 6, marginBottom: 24 },
  headerTitle: { color: "#ffffff", fontSize: 18, fontWeight: "bold", fontFamily: "Helvetica-Bold" },
  headerSub: { color: "rgba(255,255,255,0.8)", fontSize: 11, marginTop: 6 },
  investment: { color: "#F59E0B", fontSize: 14, fontWeight: "bold", fontFamily: "Helvetica-Bold", marginTop: 8 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 9, color: "#6b7280", textTransform: "uppercase", letterSpacing: 1, marginBottom: 6, fontFamily: "Helvetica-Bold" },
  sectionBody: { fontSize: 11, color: "#374151", lineHeight: 1.5 },
  divider: { borderBottomWidth: 1, borderBottomColor: "#e5e7eb", marginVertical: 12 },
  services: { flexDirection: "row", flexWrap: "wrap", gap: 4 },
  serviceBadge: { backgroundColor: "#f0fdf4", borderWidth: 1, borderColor: "#99f6e4", padding: "3 6", borderRadius: 4, fontSize: 9, color: "#0d9488" },
  footer: { marginTop: 24, paddingTop: 12, borderTopWidth: 1, borderTopColor: "#e5e7eb" },
  footerText: { fontSize: 9, color: "#9ca3af", textAlign: "center" },
});

function ProposalPDFDocument({ proposal }: { proposal: ProposalWithLead }) {
  const content = proposal.content as Record<string, string> | null;
  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.headerTitle}>{proposal.title}</Text>
          <Text style={pdfStyles.headerSub}>
            Prepared for {proposal.lead?.firstName} {proposal.lead?.lastName} — {proposal.lead?.company}
          </Text>
          <Text style={pdfStyles.investment}>
            Investment: {formatCurrency(proposal.investment ?? 0)}
          </Text>
        </View>

        {proposal.services && proposal.services.length > 0 && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>Services</Text>
            <View style={pdfStyles.services}>
              {proposal.services.map((s, i) => (
                <Text key={i} style={pdfStyles.serviceBadge}>{s}</Text>
              ))}
            </View>
          </View>
        )}

        {content && Object.entries(content).map(([key, val]) => (
          <View key={key} style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>{key.replace(/([A-Z])/g, " $1").trim()}</Text>
            <Text style={pdfStyles.sectionBody}>{val}</Text>
          </View>
        ))}

        <View style={pdfStyles.footer}>
          <Text style={pdfStyles.footerText}>
            Generated by Sales War Machine · {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
          </Text>
        </View>
      </Page>
    </Document>
  );
}

async function downloadProposalPDF(proposal: ProposalWithLead) {
  const blob = await pdf(<ProposalPDFDocument proposal={proposal} />).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `proposal-${proposal.title.toLowerCase().replace(/\s+/g, "-")}.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}

import {
  DndContext,
  DragOverlay,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
  type DragStartEvent,
} from "@dnd-kit/core";
import { useDraggable, useDroppable } from "@dnd-kit/core";

const PROPOSAL_STATUSES = ["draft", "sent", "viewed", "negotiating", "closed_won", "closed_lost"] as const;

const KANBAN_COLUMNS: { status: typeof PROPOSAL_STATUSES[number]; label: string; color: string }[] = [
  { status: "draft", label: "Draft", color: "#6B7280" },
  { status: "sent", label: "Sent", color: "#3B82F6" },
  { status: "viewed", label: "Viewed", color: "#F59E0B" },
  { status: "negotiating", label: "Negotiating", color: "#8B5CF6" },
  { status: "closed_won", label: "Closed Won", color: "#1A7A45" },
  { status: "closed_lost", label: "Closed Lost", color: "#EF4444" },
];

function ProposalCard({ proposal, isDragging }: { proposal: ProposalWithLead; isDragging?: boolean }) {
  const { attributes, listeners, setNodeRef, transform } = useDraggable({ id: proposal.id });
  const style = transform ? { transform: `translate3d(${transform.x}px, ${transform.y}px, 0)` } : undefined;
  return (
    <div
      ref={setNodeRef}
      style={{ ...(style ?? {}), }}
      {...listeners}
      {...attributes}
      className={cn(
        "rounded border border-gray-200 p-2.5 cursor-grab active:cursor-grabbing transition-colors",
        isDragging ? "opacity-50" : "hover:border-gray-200/60",
      )}
    >
      <div className="text-[11px] font-medium text-foreground truncate mb-1">{proposal.title}</div>
      <div className="text-[10px] text-muted-foreground truncate">{proposal.lead?.company}</div>
      <div className="text-[11px] font-bold mt-1.5" style={{ color: "#F59E0B" }}>{formatCurrency(proposal.investment ?? 0)}</div>
      <div className="text-[10px] text-gray-400 mt-0.5">{formatDate(proposal.createdAt)}</div>
    </div>
  );
}

function KanbanColumn({ col, proposals }: { col: typeof KANBAN_COLUMNS[number]; proposals: ProposalWithLead[] }) {
  const { isOver, setNodeRef } = useDroppable({ id: col.status });
  const colValue = proposals.reduce((sum, p) => sum + (p.investment ?? 0), 0);
  return (
    <div
      ref={setNodeRef}
      className={cn("flex-1 min-w-[140px] rounded-lg border transition-colors", isOver ? "border-teal-300" : "border-gray-200")}
      style={{ background: isOver ? "#F0FDF4" : "#F9FAFB" }}
    >
      <div className="px-3 py-2.5 border-b border-gray-200 flex items-center justify-between">
        <div className="flex items-center gap-1.5">
          <div className="w-2 h-2 rounded-full" style={{ background: col.color }} />
          <span className="text-[11px] font-semibold text-foreground">{col.label}</span>
          <span className="text-[10px] text-muted-foreground bg-gray-50 px-1.5 rounded">{proposals.length}</span>
        </div>
      </div>
      {colValue > 0 && (
        <div className="px-3 py-1.5 border-b border-gray-100">
          <span className="text-[10px] font-bold" style={{ color: col.color }}>{formatCurrency(colValue)}</span>
        </div>
      )}
      <div className="p-2 space-y-2 overflow-y-auto" style={{ maxHeight: "calc(100vh - 240px)" }}>
        {proposals.length === 0 && (
          <div className={cn("text-center py-6 text-[10px] rounded border border-dashed transition-colors", isOver ? "border-teal-200 text-teal-600/50" : "border-gray-100 text-gray-400")}>
            {isOver ? "Drop here" : "—"}
          </div>
        )}
        {proposals.map((p) => (
          <ProposalCard key={p.id} proposal={p} />
        ))}
      </div>
    </div>
  );
}

export default function Proposals() {
  const qc = useQueryClient();
  const { data: proposalsRaw = [], isLoading } = useListProposals({ query: { queryKey: getListProposalsQueryKey() } });
  const proposals = proposalsRaw as ProposalWithLead[];
  const { data: leadsPage } = useListLeads({}, { query: { queryKey: getListLeadsQueryKey() } });
  const leads: Lead[] = leadsPage?.leads ?? [];

  const createProposal = useCreateProposal({
    mutation: { onSuccess: () => { qc.invalidateQueries({ queryKey: getListProposalsQueryKey() }); setShowCreate(false); } },
  });
  const updateProposalStatus = useUpdateProposalStatus({
    mutation: { onSuccess: () => qc.invalidateQueries({ queryKey: getListProposalsQueryKey() }) },
  });
  const updateProposal = useUpdateProposal({
    mutation: { onSuccess: () => qc.invalidateQueries({ queryKey: getListProposalsQueryKey() }) },
  });
  const generateProposal = useGenerateProposal({
    mutation: { onSuccess: () => { qc.invalidateQueries({ queryKey: getListProposalsQueryKey() }); } },
  });
  const sendEmail = useSendProposalEmail({
    mutation: {
      onSuccess: (data: SendProposalEmailResult) => {
        setEmailResult(data);
        setShowEmailModal(false);
      },
    },
  });

  const [showCreate, setShowCreate] = useState(false);
  const [activeId, setActiveId] = useState<number | null>(null);
  const [editMode, setEditMode] = useState(false);
  const [editBody, setEditBody] = useState("");
  const [viewMode, setViewMode] = useState<"list" | "pipeline">("list");
  const [draggingId, setDraggingId] = useState<number | null>(null);
  const [pdfLoading, setPdfLoading] = useState(false);
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [emailSubject, setEmailSubject] = useState("");
  const [emailMessage, setEmailMessage] = useState("");
  const [emailResult, setEmailResult] = useState<SendProposalEmailResult | null>(null);

  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }));

  const activeProposal = proposals.find((p) => p.id === activeId);
  const draggingProposal = proposals.find((p) => p.id === draggingId);

  const pipelineValue = proposals.filter((p) => p.status !== "closed_lost").reduce((sum, p) => sum + (p.investment ?? 0), 0);

  const handleCreate = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    const services = String(fd.get("services")).split(",").map((s) => s.trim()).filter(Boolean);
    createProposal.mutate({
      data: {
        leadId: Number(fd.get("leadId")),
        title: String(fd.get("title")),
        services,
        investment: Number(fd.get("investment")),
      },
    });
  };

  const handleDragStart = (event: DragStartEvent) => {
    setDraggingId(Number(event.active.id));
  };

  const handleDragEnd = (event: DragEndEvent) => {
    setDraggingId(null);
    const { active, over } = event;
    if (!over) return;
    const proposalId = Number(active.id);
    const newStatus = String(over.id) as typeof PROPOSAL_STATUSES[number];
    const proposal = proposals.find((p) => p.id === proposalId);
    if (!proposal || proposal.status === newStatus) return;
    updateProposalStatus.mutate({ id: proposalId, data: { status: newStatus } });
  };

  return (
    <div className="p-3 md:p-6 space-y-3 md:space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-lg font-bold text-foreground">Proposal Engine</h1>
          <p className="text-xs text-muted-foreground mt-0.5">{proposals.length} proposals · Pipeline: <span className="font-semibold" style={{ color: "#F59E0B" }}>{formatCurrency(pipelineValue)}</span></p>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex gap-1 border border-gray-200 rounded p-0.5">
            <button
              onClick={() => setViewMode("list")}
              className={cn("p-1.5 rounded transition-colors", viewMode === "list" ? "bg-gray-100 text-foreground" : "text-muted-foreground hover:text-gray-900")}
              title="List view"
            >
              <LayoutList className="w-3.5 h-3.5" />
            </button>
            <button
              onClick={() => setViewMode("pipeline")}
              className={cn("p-1.5 rounded transition-colors", viewMode === "pipeline" ? "bg-gray-100 text-foreground" : "text-muted-foreground hover:text-gray-900")}
              title="Pipeline (Kanban) view"
            >
              <Columns3 className="w-3.5 h-3.5" />
            </button>
          </div>
          <button onClick={() => setShowCreate(true)} className="flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-medium text-white" style={{ background: "#1A7A45" }}>
            <Plus className="w-3.5 h-3.5" /> New Proposal
          </button>
        </div>
      </div>

      {viewMode === "pipeline" ? (
        <DndContext sensors={sensors} onDragStart={handleDragStart} onDragEnd={handleDragEnd}>
          <div className="overflow-x-auto">
            <div className="flex gap-3" style={{ minWidth: "900px", paddingBottom: "16px" }}>
              {KANBAN_COLUMNS.map((col) => {
                const colProposals = proposals.filter((p) => p.status === col.status);
                return <KanbanColumn key={col.status} col={col} proposals={colProposals} />;
              })}
            </div>
          </div>
          <DragOverlay>
            {draggingProposal ? (
              <div className="rounded border border-teal-300 p-2.5 shadow-xl" style={{ width: "160px" }}>
                <div className="text-[11px] font-medium text-foreground truncate mb-1">{draggingProposal.title}</div>
                <div className="text-[10px] text-muted-foreground truncate">{draggingProposal.lead?.company}</div>
                <div className="text-[11px] font-bold mt-1.5" style={{ color: "#F59E0B" }}>{formatCurrency(draggingProposal.investment ?? 0)}</div>
              </div>
            ) : null}
          </DragOverlay>
        </DndContext>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
          <div className="md:col-span-2 rounded-lg border border-gray-200 overflow-hidden flex flex-col" style={{ maxHeight: "calc(100vh - 180px)" }}>
            <div className="px-3 py-2.5 border-b border-gray-200 text-[11px] font-semibold text-muted-foreground uppercase tracking-wider">Proposals</div>
            <div className="flex-1 overflow-y-auto divide-y divide-border/30">
              {isLoading ? (
                <div className="p-4 space-y-2">{[1, 2].map((i) => <div key={i} className="h-16 rounded animate-pulse" />)}</div>
              ) : proposals.length === 0 ? (
                <div className="p-8 text-center text-xs text-muted-foreground">
                  <FileText className="w-6 h-6 mx-auto mb-2 opacity-40" />
                  No proposals yet
                </div>
              ) : proposals.map((p) => (
                <button
                  key={p.id}
                  onClick={() => { setActiveId(p.id); setEditMode(false); setEditBody(""); }}
                  className={cn("w-full text-left px-3 py-3 hover:bg-gray-50 transition-colors", activeId === p.id && "bg-teal-50 border-l-2 border-teal-500")}
                >
                  <div className="text-xs font-medium text-foreground truncate">{p.title}</div>
                  <div className="text-[11px] text-muted-foreground">{p.lead?.firstName} {p.lead?.lastName} · {p.lead?.company}</div>
                  <div className="flex items-center gap-2 mt-1">
                    <StatusBadge status={p.status} />
                    <span className="text-[11px] font-bold" style={{ color: "#F59E0B" }}>{formatCurrency(p.investment ?? 0)}</span>
                  </div>
                  <div className="text-[10px] text-gray-400 mt-1">{formatDate(p.createdAt)}</div>
                </button>
              ))}
            </div>
          </div>

          <div className="md:col-span-3 space-y-3 overflow-y-auto" style={{ maxHeight: "calc(100vh - 180px)" }}>
            {!activeProposal ? (
              <div className="rounded-lg border border-dashed border-gray-200 p-12 text-center">
                <FileText className="w-8 h-8 text-muted-foreground mx-auto mb-3" />
                <div className="text-sm text-muted-foreground">Select a proposal to view</div>
              </div>
            ) : (
              <>
                <div className="rounded-xl border border-gray-200 p-4 bg-white shadow-sm">
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <div className="text-sm font-bold text-foreground">{activeProposal.title}</div>
                      <div className="text-xs text-muted-foreground mt-0.5">{activeProposal.lead?.firstName} {activeProposal.lead?.lastName} — {activeProposal.lead?.company}</div>
                      <div className="flex items-center gap-3 mt-2">
                        <StatusBadge status={activeProposal.status} />
                        <span className="text-sm font-black" style={{ color: "#F59E0B" }}>{formatCurrency(activeProposal.investment ?? 0)}</span>
                      </div>
                    </div>
                    <select
                      value={activeProposal.status}
                      onChange={(e) => updateProposalStatus.mutate({ id: activeProposal.id, data: { status: e.target.value } })}
                      className="text-xs rounded border border-gray-200 bg-white text-gray-900 px-2 py-1 focus:outline-none"
                    >
                      {PROPOSAL_STATUSES.map((s) => <option key={s} value={s}>{s.replace(/_/g, " ")}</option>)}
                    </select>
                  </div>

                  {activeProposal.services?.length > 0 && (
                    <div className="mt-3 pt-3 border-t border-gray-200">
                      <div className="text-[11px] text-muted-foreground uppercase tracking-wider mb-2">Services</div>
                      <div className="flex flex-wrap gap-1">
                        {activeProposal.services.map((svc, i) => (
                          <span key={i} className="text-[11px] px-1.5 py-0.5 rounded bg-teal-50 text-teal-700 border border-teal-200">{svc}</span>
                        ))}
                      </div>
                    </div>
                  )}

                  <div className="flex flex-wrap gap-2 mt-3">
                    <button
                      onClick={() => generateProposal.mutate({ id: activeProposal.id })}
                      disabled={generateProposal.isPending}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-medium text-white disabled:opacity-50"
                      style={{ background: "#1A7A45" }}
                    >
                      <Zap className="w-3.5 h-3.5" /> {generateProposal.isPending ? "Generating..." : "AI Generate Body"}
                    </button>
                    {activeProposal.content && (
                      <button onClick={() => setEditMode(!editMode)} className="flex items-center gap-1.5 px-3 py-1.5 rounded text-xs border border-gray-200 text-muted-foreground hover:text-gray-900">
                        <Edit2 className="w-3.5 h-3.5" /> {editMode ? "Cancel Edit" : "Edit"}
                      </button>
                    )}
                    <button
                      onClick={async () => {
                        setPdfLoading(true);
                        try { await downloadProposalPDF(activeProposal); } finally { setPdfLoading(false); }
                      }}
                      disabled={pdfLoading}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded text-xs border border-gray-200 text-muted-foreground hover:text-gray-900 disabled:opacity-50"
                    >
                      <Download className="w-3.5 h-3.5" /> {pdfLoading ? "Exporting..." : "Export PDF"}
                    </button>
                    <button
                      onClick={() => {
                        setEmailSubject(`Proposal: ${activeProposal.title}`);
                        setEmailMessage("");
                        setEmailResult(null);
                        setShowEmailModal(true);
                      }}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded text-xs border border-gray-200 text-muted-foreground hover:text-gray-900"
                    >
                      <Mail className="w-3.5 h-3.5" /> Email to Lead
                    </button>
                  </div>

                  {emailResult && (
                    <div className="mt-3 rounded-lg border border-green-200 p-3 text-xs" style={{ background: "rgba(22,163,74,0.05)" }}>
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-1.5 text-green-700 font-semibold">
                          <Mail className="w-3.5 h-3.5" /> Email sent to {emailResult.to || "test inbox"}
                        </div>
                        <button onClick={() => setEmailResult(null)} className="text-gray-400 hover:text-gray-600"><X className="w-3 h-3" /></button>
                      </div>
                      <div className="text-muted-foreground mt-1">Subject: {emailResult.subject}</div>
                      {emailResult.deliveryMode === "test" && (
                        <div className="text-amber-600 mt-1 text-[11px]">Sent via test inbox (no SMTP configured)</div>
                      )}
                      {emailResult.preview && (
                        <a href={emailResult.preview} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-teal-600 mt-1 hover:underline">
                          <ExternalLink className="w-3 h-3" /> Preview email (Ethereal test)
                        </a>
                      )}
                    </div>
                  )}
                </div>

                {activeProposal.followups && activeProposal.followups.length > 0 && (
                  <div className="rounded-xl border border-gray-200 p-4 bg-white shadow-sm">
                    <div className="text-xs font-semibold text-foreground uppercase tracking-wider mb-3">Follow-up Tracker</div>
                    <div className="space-y-2">
                      {activeProposal.followups.map((fu, i) => {
                        const f = fu as { timing?: string; channel?: string; status?: string; label?: string };
                        return (
                          <div key={i} className="flex items-center gap-3 text-xs">
                            <span className="w-10 text-muted-foreground font-mono text-[11px]">{f.timing}</span>
                            <span className="capitalize text-gray-700">{f.channel}</span>
                            <span className={cn("px-1.5 py-0.5 rounded text-[11px]", f.status === "sent" ? "bg-green-50 text-green-700" : "bg-gray-50 text-muted-foreground")}>{f.status}</span>
                            {f.label && <span className="text-gray-400 text-[10px] truncate">{f.label}</span>}
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

                <div className="rounded-xl border border-gray-200 p-4 bg-white shadow-sm">
                  <div className="text-xs font-semibold text-foreground uppercase tracking-wider mb-3">Proposal Content</div>
                  {activeProposal.content ? (
                    editMode ? (
                      <div className="space-y-2">
                        <textarea
                          value={editBody}
                          onChange={(e) => setEditBody(e.target.value)}
                          rows={10}
                          className="w-full text-xs rounded border border-gray-200 bg-white text-gray-900 px-3 py-2 focus:outline-none resize-none"
                        />
                        <button
                          onClick={() => { updateProposal.mutate({ id: activeProposal.id, data: { content: { mirror: editBody } } }); setEditMode(false); }}
                          className="px-3 py-1.5 rounded text-xs text-white font-medium"
                          style={{ background: "#1A7A45" }}
                        >
                          Save Changes
                        </button>
                      </div>
                    ) : (
                      <div className="space-y-3">
                        {Object.entries(activeProposal.content as Record<string, string>).map(([key, val]) => (
                          <div key={key}>
                            <div className="text-[11px] text-muted-foreground uppercase tracking-wider mb-1">{key.replace(/([A-Z])/g, " $1").trim()}</div>
                            <div className="text-xs text-gray-700 leading-relaxed">{val as string}</div>
                          </div>
                        ))}
                      </div>
                    )
                  ) : (
                    <div className="text-xs text-muted-foreground italic">No content yet. Click "AI Generate Body" to create the proposal.</div>
                  )}
                </div>
              </>
            )}
          </div>
        </div>
      )}

      {showCreate && (
        <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50" onClick={() => setShowCreate(false)}>
          <div className="rounded-xl border border-gray-200 p-6 w-full max-w-md bg-white shadow-sm" onClick={(e) => e.stopPropagation()}>
            <h2 className="text-sm font-bold text-foreground mb-4">New Proposal</h2>
            <form onSubmit={handleCreate} className="space-y-3">
              <div>
                <label className="block text-[11px] text-muted-foreground mb-1">Lead</label>
                <select name="leadId" required className="w-full text-xs rounded border border-gray-200 bg-white text-gray-900 px-2.5 py-1.5 focus:outline-none">
                  <option value="">Select lead...</option>
                  {leads.map((l) => <option key={l.id} value={l.id}>{l.firstName} {l.lastName} — {l.company}</option>)}
                </select>
              </div>
              <div>
                <label className="block text-[11px] text-muted-foreground mb-1">Proposal Title</label>
                <input name="title" required placeholder="Brand Identity & Digital Presence Package" className="w-full text-xs rounded border border-gray-200 bg-white text-gray-900 px-2.5 py-1.5 focus:outline-none" />
              </div>
              <div>
                <label className="block text-[11px] text-muted-foreground mb-1">Investment (USD)</label>
                <input name="investment" required type="number" placeholder="15000" className="w-full text-xs rounded border border-gray-200 bg-white text-gray-900 px-2.5 py-1.5 focus:outline-none" />
              </div>
              <div>
                <label className="block text-[11px] text-muted-foreground mb-1">Services (comma separated)</label>
                <input name="services" placeholder="Brand Strategy, Logo Design, Website" className="w-full text-xs rounded border border-gray-200 bg-white text-gray-900 px-2.5 py-1.5 focus:outline-none" />
              </div>
              <div className="flex gap-2 pt-2">
                <button type="button" onClick={() => setShowCreate(false)} className="flex-1 px-3 py-1.5 rounded text-xs text-muted-foreground bg-gray-50 border border-gray-200">Cancel</button>
                <button type="submit" disabled={createProposal.isPending} className="flex-1 px-3 py-1.5 rounded text-xs text-white font-medium" style={{ background: "#1A7A45" }}>
                  {createProposal.isPending ? "Creating..." : "Create Proposal"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {showEmailModal && activeProposal && (
        <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50" onClick={() => setShowEmailModal(false)}>
          <div className="rounded-xl border border-gray-200 p-6 w-full max-w-md bg-white shadow-sm" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-sm font-bold text-foreground">Email Proposal to Lead</h2>
              <button onClick={() => setShowEmailModal(false)} className="text-gray-400 hover:text-gray-600"><X className="w-4 h-4" /></button>
            </div>
            <div className="mb-3 p-3 rounded-lg border border-gray-100 text-xs text-muted-foreground">
              <span className="font-medium text-foreground">{activeProposal.lead?.firstName} {activeProposal.lead?.lastName}</span>
              {activeProposal.lead?.email && <span> · {activeProposal.lead.email}</span>}
              <span className="text-gray-400 ml-1">({activeProposal.lead?.company})</span>
            </div>
            <div className="space-y-3">
              <div>
                <label className="block text-[11px] text-muted-foreground mb-1">Subject</label>
                <input
                  value={emailSubject}
                  onChange={(e) => setEmailSubject(e.target.value)}
                  className="w-full text-xs rounded border border-gray-200 bg-white text-gray-900 px-2.5 py-1.5 focus:outline-none"
                  placeholder="Proposal: ..."
                />
              </div>
              <div>
                <label className="block text-[11px] text-muted-foreground mb-1">Personal message (optional)</label>
                <textarea
                  value={emailMessage}
                  onChange={(e) => setEmailMessage(e.target.value)}
                  rows={3}
                  className="w-full text-xs rounded border border-gray-200 bg-white text-gray-900 px-3 py-2 focus:outline-none resize-none"
                  placeholder="Hi John, I've put together a proposal for your review..."
                />
              </div>
              {!activeProposal.lead?.email && (
                <div className="text-[11px] text-amber-600 bg-amber-50 border border-amber-200 rounded p-2">
                  No email on file for this lead — email will be sent to a test inbox.
                </div>
              )}
              <div className="flex gap-2 pt-1">
                <button type="button" onClick={() => setShowEmailModal(false)} className="flex-1 px-3 py-1.5 rounded text-xs text-muted-foreground bg-gray-50 border border-gray-200">Cancel</button>
                <button
                  disabled={sendEmail.isPending}
                  onClick={() => sendEmail.mutate({ id: activeProposal.id, data: { subject: emailSubject, message: emailMessage } })}
                  className="flex-1 flex items-center justify-center gap-1.5 px-3 py-1.5 rounded text-xs text-white font-medium disabled:opacity-50"
                  style={{ background: "#1A7A45" }}
                >
                  <Mail className="w-3.5 h-3.5" />
                  {sendEmail.isPending ? "Sending..." : "Send Email"}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
