import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import icpRouter from "./icp";
import leadsRouter from "./leads";
import auditRouter from "./audit";
import qualifyRouter from "./qualify";
import outreachRouter from "./outreach";
import meetingsRouter from "./meetings";
import proposalsRouter from "./proposals";
import anthropicRouter from "./anthropic";
import fetchLeadsRouter from "./fetch-leads";
import settingsRouter from "./settings";
import outreachAiRouter from "./outreach-ai";
import appointmentsRouter from "./appointments";
import searchRouter from "./search";
import trackingRouter from "./tracking";
import hubspotRouter from "./hubspot";
import whatsappRouter from "./whatsapp";
import integrationsRouter from "./integrations";
import brainRouter from "./brain";
import leadBankRouter from "./lead-bank";
import agentsRouter from "./agents";
import campaignsRouter from "./campaigns";
import waitlistRouter from "./waitlist";
import salesAgentRouter from "./sales-agent";
import stripeRouter from "./stripe";
import superAdminRouter from "./super-admin";
import feedbackRouter from "./feedback";
import leadListsRouter from "./lead-lists";
import teamRouter from "./team";
import oauthRouter from "./oauth";
import otpRouter from "./otp";
import agentHubRouter from "./agent-hub";
import billingRouter from "./billing";
import signalsRouter from "./signals";
import bantbBatchRouter from "./bantb-batch";
import playsRouter from "./plays";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(oauthRouter);
router.use(otpRouter);
router.use(dashboardRouter);
router.use(icpRouter);
router.use(fetchLeadsRouter);
router.use(leadsRouter);
router.use(auditRouter);
router.use(qualifyRouter);
router.use(outreachRouter);
router.use(meetingsRouter);
router.use(proposalsRouter);
router.use(anthropicRouter);
router.use(settingsRouter);
router.use(outreachAiRouter);
router.use(appointmentsRouter);
router.use(searchRouter);
router.use(trackingRouter);
router.use("/hubspot", hubspotRouter);
router.use(whatsappRouter);
router.use(integrationsRouter);
router.use(brainRouter);
router.use(leadBankRouter);
router.use(agentsRouter);
router.use(agentHubRouter);
router.use(campaignsRouter);
router.use(waitlistRouter);
router.use(salesAgentRouter);
router.use(stripeRouter);
router.use(billingRouter);
router.use(teamRouter);
router.use(superAdminRouter);
router.use(feedbackRouter);
router.use(leadListsRouter);
router.use("/signal-feed", signalsRouter);
router.use(bantbBatchRouter);
router.use(playsRouter);

export default router;
