import { db } from "@workspace/db";
  import { leads } from "@workspace/db/schema";
  import { inArray } from "drizzle-orm";

  const MISSING_LEADS = [
  {
    "first_name": "Layla",
    "last_name": "Al Mansouri",
    "email": "layla.almansouri@lumineretail.ae",
    "company": "Lumine Retail Group",
    "designation": "Chief Executive Officer",
    "industry": "Retail",
    "country": "UAE",
    "phone": "+971501234567",
    "website": "https://www.lumineretail.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/layla-almansouri-ceo",
    "city": "Dubai"
  },
  {
    "first_name": "Tariq",
    "last_name": "Al Rashidi",
    "email": "tariq.rashidi@zayanhome.com",
    "company": "Zayan Home & Lifestyle",
    "designation": "Chief Marketing Officer",
    "industry": "Retail",
    "country": "Saudi Arabia",
    "phone": "+966501987654",
    "website": "https://www.zayanhome.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/tariq-alrashidi-cmo",
    "city": "Riyadh"
  },
  {
    "first_name": "Nour",
    "last_name": "Khalifa",
    "email": "nour.khalifa@modestaefashion.ae",
    "company": "Modesta Fashion LLC",
    "designation": "Marketing Director",
    "industry": "Fashion",
    "country": "UAE",
    "phone": "+971554321890",
    "website": "https://www.modestaefashion.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/nour-khalifa-marketing",
    "city": "Abu Dhabi"
  },
  {
    "first_name": "Faisal",
    "last_name": "Al Otaibi",
    "email": "faisal.alotaibi@soukdigital.sa",
    "company": "Souk Digital Commerce",
    "designation": "Chief Executive Officer",
    "industry": "E-commerce",
    "country": "Saudi Arabia",
    "phone": "+966559876543",
    "website": "https://www.soukdigital.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/faisal-alotaibi-ecommerce",
    "city": "Jeddah"
  },
  {
    "first_name": "Rania",
    "last_name": "Hamdan",
    "email": "rania.hamdan@eleganzagroup.ae",
    "company": "Eleganza Fashion Group",
    "designation": "CMO",
    "industry": "Fashion",
    "country": "UAE",
    "phone": "+971507654321",
    "website": "https://www.eleganzagroup.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/rania-hamdan-cmo-dubai",
    "city": "Dubai"
  },
  {
    "first_name": "Omar",
    "last_name": "Al Zaabi",
    "email": "omar.alzaabi@perlabeauty.ae",
    "company": "Perla Beauty & Retail",
    "designation": "Chief Executive Officer",
    "industry": "Retail",
    "country": "UAE",
    "phone": "+971523456789",
    "website": "https://www.perlabeauty.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/omar-alzaabi-retail-ceo",
    "city": "Sharjah"
  },
  {
    "first_name": "Sara",
    "last_name": "Al Ghamdi",
    "email": "sara.alghamdi@novacommerce.sa",
    "company": "Nova Commerce Arabia",
    "designation": "Marketing Director",
    "industry": "E-commerce",
    "country": "Saudi Arabia",
    "phone": "+966534567890",
    "website": "https://www.novacommerce.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/sara-alghamdi-marketing-ksa",
    "city": "Riyadh"
  },
  {
    "first_name": "Khalid",
    "last_name": "Bin Saeed",
    "email": "khalid.binsaeed@threadsplusae.com",
    "company": "Threads+ Fashion Retail",
    "designation": "Chief Marketing Officer",
    "industry": "Fashion",
    "country": "UAE",
    "phone": "+971556789012",
    "website": "https://www.threadsplusae.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/khalid-binsaeed-fashion-cmo",
    "city": "Dubai"
  },
  {
    "first_name": "Amira",
    "last_name": "Youssef",
    "email": "amira.youssef@cartexpress.ae",
    "company": "CartExpress MENA",
    "designation": "CEO",
    "industry": "E-commerce",
    "country": "UAE",
    "phone": "+971509871234",
    "website": "https://www.cartexpress.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/amira-youssef-cartexpress",
    "city": "Dubai"
  },
  {
    "first_name": "Yusuf",
    "last_name": "Al Harbi",
    "email": "yusuf.alharbi@majalislifestyle.sa",
    "company": "Majalis Lifestyle Retail",
    "designation": "Marketing Director",
    "industry": "Retail",
    "country": "Saudi Arabia",
    "phone": "+966503214567",
    "website": "https://www.majalislifestyle.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/yusuf-alharbi-lifestyle-marketing",
    "city": "Jeddah"
  },
  {
    "first_name": "Layla",
    "last_name": "Al Mansoori",
    "email": "layla.almansoori@modavistaae.com",
    "company": "Moda Vista UAE",
    "designation": "Chief Executive Officer",
    "industry": "Fashion Retail",
    "country": "UAE",
    "phone": "+971501234567",
    "website": "https://www.modavistaae.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/layla-almansoori-ceo",
    "city": "Dubai"
  },
  {
    "first_name": "Tariq",
    "last_name": "Al Rashidi",
    "email": "tariq.alrashidi@golfsouq.sa",
    "company": "Gulf Souq Commerce",
    "designation": "Chief Marketing Officer",
    "industry": "E-commerce",
    "country": "Saudi Arabia",
    "phone": "+966551234567",
    "website": "https://www.golfsouq.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/tariq-alrashidi-cmo",
    "city": "Riyadh"
  },
  {
    "first_name": "Noor",
    "last_name": "Khalifa",
    "email": "noor.khalifa@siennastyle.ae",
    "company": "Sienna Style Group",
    "designation": "Marketing Director",
    "industry": "Fashion",
    "country": "UAE",
    "phone": "+971521234567",
    "website": "https://www.siennastyle.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/noor-khalifa-marketing",
    "city": "Abu Dhabi"
  },
  {
    "first_name": "Omar",
    "last_name": "Basrawi",
    "email": "omar.basrawi@nexaretail.ae",
    "company": "Nexa Retail Solutions",
    "designation": "Chief Executive Officer",
    "industry": "Retail",
    "country": "UAE",
    "phone": "+971561234567",
    "website": "https://www.nexaretail.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/omar-basrawi-nexaretail",
    "city": "Dubai"
  },
  {
    "first_name": "Fatima",
    "last_name": "Al Zaabi",
    "email": "fatima.alzaabi@threadsnco.com",
    "company": "Threads & Co. Fashion",
    "designation": "CMO",
    "industry": "Fashion Retail",
    "country": "UAE",
    "phone": "+971531234567",
    "website": "https://www.threadsnco.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/fatima-alzaabi-threads",
    "city": "Sharjah"
  },
  {
    "first_name": "Hassan",
    "last_name": "Al Otaibi",
    "email": "hassan.alotaibi@zenithcommerce.sa",
    "company": "Zenith Commerce KSA",
    "designation": "Chief Executive Officer",
    "industry": "E-commerce",
    "country": "Saudi Arabia",
    "phone": "+966561234567",
    "website": "https://www.zenithcommerce.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/hassan-alotaibi-zenith",
    "city": "Jeddah"
  },
  {
    "first_name": "Rania",
    "last_name": "Hamdan",
    "email": "rania.hamdan@luxeloopuae.com",
    "company": "LuxeLoop UAE",
    "designation": "Marketing Director",
    "industry": "Fashion",
    "country": "UAE",
    "phone": "+971541234567",
    "website": "https://www.luxeloopuae.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/rania-hamdan-luxeloop",
    "city": "Dubai"
  },
  {
    "first_name": "Khalid",
    "last_name": "Al Shamsi",
    "email": "khalid.alshamsi@emiratetrade.ae",
    "company": "Emirate Trade Retail",
    "designation": "Chief Executive Officer",
    "industry": "Retail",
    "country": "UAE",
    "phone": "+971511234567",
    "website": "https://www.emiratetrade.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/khalid-alshamsi-emirate",
    "city": "Dubai"
  },
  {
    "first_name": "Sara",
    "last_name": "Al Ghamdi",
    "email": "sara.alghamdi@mirageboutique.sa",
    "company": "Mirage Boutique KSA",
    "designation": "Chief Marketing Officer",
    "industry": "Fashion Retail",
    "country": "Saudi Arabia",
    "phone": "+966571234567",
    "website": "https://www.mirageboutique.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/sara-alghamdi-mirage",
    "city": "Riyadh"
  },
  {
    "first_name": "Yousuf",
    "last_name": "Mahmoud",
    "email": "yousuf.mahmoud@cartdropuae.com",
    "company": "CartDrop UAE",
    "designation": "Marketing Director",
    "industry": "E-commerce",
    "country": "UAE",
    "phone": "+971551234567",
    "website": "https://www.cartdropuae.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/yousuf-mahmoud-cartdrop",
    "city": "Dubai"
  },
  {
    "first_name": "Layla",
    "last_name": "Al Rashidi",
    "email": "layla.alrashidi@modavogue.ae",
    "company": "ModaVogue Retail Group",
    "designation": "Chief Marketing Officer",
    "industry": "Fashion Retail",
    "country": "UAE",
    "phone": "+971501234567",
    "website": "https://www.modavogue.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/layla-alrashidi-cmo",
    "city": "Dubai"
  },
  {
    "first_name": "Tariq",
    "last_name": "Al Mansoori",
    "email": "tariq.almansoori@gulfstylex.com",
    "company": "GulfStyleX",
    "designation": "Chief Executive Officer",
    "industry": "E-commerce",
    "country": "UAE",
    "phone": "+971521987654",
    "website": "https://www.gulfstylex.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/tariq-almansoori-ceo",
    "city": "Abu Dhabi"
  },
  {
    "first_name": "Noor",
    "last_name": "Bint Khalid",
    "email": "noor.khalid@luxeabayas.sa",
    "company": "Luxe Abayas Co.",
    "designation": "Marketing Director",
    "industry": "Fashion",
    "country": "Saudi Arabia",
    "phone": "+966501122334",
    "website": "https://www.luxeabayas.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/noor-bintkhalid-marketing",
    "city": "Riyadh"
  },
  {
    "first_name": "Faisal",
    "last_name": "Al Otaibi",
    "email": "f.alotaibi@shopxpressme.com",
    "company": "ShopXpress Middle East",
    "designation": "Chief Executive Officer",
    "industry": "E-commerce",
    "country": "Saudi Arabia",
    "phone": "+966557890123",
    "website": "https://www.shopxpressme.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/faisal-alotaibi-shopxpress",
    "city": "Jeddah"
  },
  {
    "first_name": "Hessa",
    "last_name": "Al Maktoum",
    "email": "hessa.almaktoum@soukchicuae.ae",
    "company": "Souk Chic UAE",
    "designation": "CMO",
    "industry": "Retail",
    "country": "UAE",
    "phone": "+971554321098",
    "website": "https://www.soukchicuae.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/hessa-almaktoum-soukchic",
    "city": "Dubai"
  },
  {
    "first_name": "Omar",
    "last_name": "Al Hajri",
    "email": "omar.alhajri@threadsnation.ae",
    "company": "Threads Nation",
    "designation": "Marketing Director",
    "industry": "Fashion Retail",
    "country": "UAE",
    "phone": "+971509876543",
    "website": "https://www.threadsnation.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/omar-alhajri-threads",
    "city": "Sharjah"
  },
  {
    "first_name": "Sara",
    "last_name": "Bin Hamdan",
    "email": "sara.binhamdan@eliteretailksa.sa",
    "company": "Elite Retail KSA",
    "designation": "Chief Executive Officer",
    "industry": "Retail",
    "country": "Saudi Arabia",
    "phone": "+966533445566",
    "website": "https://www.eliteretailksa.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/sara-binhamdan-eliteretail",
    "city": "Riyadh"
  },
  {
    "first_name": "Khalid",
    "last_name": "Al Suwaidi",
    "email": "khalid.alsuwaidi@cartzone.ae",
    "company": "CartZone.ae",
    "designation": "Chief Executive Officer",
    "industry": "E-commerce",
    "country": "UAE",
    "phone": "+971561234567",
    "website": "https://www.cartzone.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/khalid-alsuwaidi-cartzone",
    "city": "Dubai"
  },
  {
    "first_name": "Mona",
    "last_name": "Al Farsi",
    "email": "mona.alfarsi@trendsetterme.ae",
    "company": "Trendsetter Middle East",
    "designation": "Marketing Director",
    "industry": "Fashion",
    "country": "UAE",
    "phone": "+971527654321",
    "website": "https://www.trendsetterme.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/mona-alfarsi-trendsetter",
    "city": "Dubai"
  },
  {
    "first_name": "Yousef",
    "last_name": "Al Zahrani",
    "email": "yousef.alzahrani@bazaarksa.sa",
    "company": "Bazaar KSA",
    "designation": "Chief Marketing Officer",
    "industry": "Retail",
    "country": "Saudi Arabia",
    "phone": "+966509988776",
    "website": "https://www.bazaarksa.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/yousef-alzahrani-bazaarksa",
    "city": "Jeddah"
  },
  {
    "first_name": "Layla",
    "last_name": "Al Mansoori",
    "email": "layla.almansoori@modahouse.ae",
    "company": "Moda House Retail Group",
    "designation": "Chief Executive Officer",
    "industry": "Fashion Retail",
    "country": "UAE",
    "phone": "+971501234567",
    "website": "https://www.modahouse.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/layla-almansoori-ceo",
    "city": "Dubai"
  },
  {
    "first_name": "Khalid",
    "last_name": "Al Rashidi",
    "email": "khalid.rashidi@gulfstylebazaar.com",
    "company": "Gulf Style Bazaar",
    "designation": "Chief Marketing Officer",
    "industry": "E-commerce",
    "country": "Saudi Arabia",
    "phone": "+966541234567",
    "website": "https://www.gulfstylebazaar.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/khalid-alrashidi-cmo",
    "city": "Riyadh"
  },
  {
    "first_name": "Sara",
    "last_name": "Haddad",
    "email": "sara.haddad@luxelevantretail.ae",
    "company": "Luxe Levant Retail",
    "designation": "Marketing Director",
    "industry": "Luxury Fashion",
    "country": "UAE",
    "phone": "+971521234567",
    "website": "https://www.luxelevantretail.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/sara-haddad-marketing",
    "city": "Abu Dhabi"
  },
  {
    "first_name": "Omar",
    "last_name": "Farouq",
    "email": "omar.farouq@trendzoneme.com",
    "company": "TrendZone Middle East",
    "designation": "CEO",
    "industry": "Fashion Retail",
    "country": "UAE",
    "phone": "+971561234567",
    "website": "https://www.trendzoneme.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/omar-farouq-trendzone",
    "city": "Dubai"
  },
  {
    "first_name": "Noor",
    "last_name": "Al Zahrani",
    "email": "noor.alzahrani@cartarabia.sa",
    "company": "Cart Arabia",
    "designation": "Chief Marketing Officer",
    "industry": "E-commerce",
    "country": "Saudi Arabia",
    "phone": "+966551234567",
    "website": "https://www.cartarabia.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/noor-alzahrani-cmo",
    "city": "Jeddah"
  },
  {
    "first_name": "Rami",
    "last_name": "Khoury",
    "email": "rami.khoury@souqdubaigroup.ae",
    "company": "Souq Dubai Group",
    "designation": "Marketing Director",
    "industry": "Retail",
    "country": "UAE",
    "phone": "+971531234567",
    "website": "https://www.souqdubaigroup.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/rami-khoury-marketing",
    "city": "Dubai"
  },
  {
    "first_name": "Aisha",
    "last_name": "Bin Saeed",
    "email": "aisha.binsaeed@eleganceemirates.ae",
    "company": "Elegance Emirates",
    "designation": "Chief Executive Officer",
    "industry": "Fashion",
    "country": "UAE",
    "phone": "+971541234567",
    "website": "https://www.eleganceemirates.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/aisha-binsaeed-ceo",
    "city": "Sharjah"
  },
  {
    "first_name": "Faisal",
    "last_name": "Al Otaibi",
    "email": "faisal.alotaibi@clickmartsa.com",
    "company": "ClickMart Saudi Arabia",
    "designation": "CEO",
    "industry": "E-commerce",
    "country": "Saudi Arabia",
    "phone": "+966561234567",
    "website": "https://www.clickmartsa.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/faisal-alotaibi-clickmart",
    "city": "Riyadh"
  },
  {
    "first_name": "Mariam",
    "last_name": "El Sheikh",
    "email": "mariam.elsheikh@voyagefashionuae.com",
    "company": "Voyage Fashion UAE",
    "designation": "Marketing Director",
    "industry": "Fashion Retail",
    "country": "UAE",
    "phone": "+971511234567",
    "website": "https://www.voyagefashionuae.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/mariam-elsheikh-voyagefashion",
    "city": "Dubai"
  },
  {
    "first_name": "Tariq",
    "last_name": "Al Harbi",
    "email": "tariq.alharbi@nakheelacommerce.sa",
    "company": "Nakheela Commerce",
    "designation": "Chief Marketing Officer",
    "industry": "Retail",
    "country": "Saudi Arabia",
    "phone": "+966531234567",
    "website": "https://www.nakheelacommerce.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/tariq-alharbi-nakheela",
    "city": "Dammam"
  },
  {
    "first_name": "Layla",
    "last_name": "Al-Rashidi",
    "email": "layla.alrashidi@modahaus.ae",
    "company": "ModaHaus Retail Group",
    "designation": "Chief Marketing Officer",
    "industry": "Fashion Retail",
    "country": "UAE",
    "phone": "+971501234567",
    "website": "https://www.modahaus.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/layla-alrashidi-cmo",
    "city": "Dubai"
  },
  {
    "first_name": "Tariq",
    "last_name": "Bin Hamdan",
    "email": "t.binhamdan@zestcommerce.sa",
    "company": "Zest Commerce Arabia",
    "designation": "Chief Executive Officer",
    "industry": "E-commerce",
    "country": "Saudi Arabia",
    "phone": "+966502345678",
    "website": "https://www.zestcommerce.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/tariq-binhamdan-ceo",
    "city": "Riyadh"
  },
  {
    "first_name": "Nour",
    "last_name": "Al-Farsi",
    "email": "nour.alfarsi@eleganzauae.com",
    "company": "Eleganza Fashion UAE",
    "designation": "Marketing Director",
    "industry": "Fashion",
    "country": "UAE",
    "phone": "+971521345678",
    "website": "https://www.eleganzauae.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/nour-alfarsi-marketing",
    "city": "Abu Dhabi"
  },
  {
    "first_name": "Khalid",
    "last_name": "Mansouri",
    "email": "khalid.mansouri@souqelite.ae",
    "company": "Souq Elite Trading LLC",
    "designation": "CEO",
    "industry": "Retail",
    "country": "UAE",
    "phone": "+971551456789",
    "website": "https://www.souqelite.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/khalid-mansouri-dubai",
    "city": "Dubai"
  },
  {
    "first_name": "Sara",
    "last_name": "Al-Otaibi",
    "email": "sara.alotaibi@threadsnco.sa",
    "company": "Threads & Co. KSA",
    "designation": "Chief Marketing Officer",
    "industry": "Fashion E-commerce",
    "country": "Saudi Arabia",
    "phone": "+966503456789",
    "website": "https://www.threadsnco.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/sara-alotaibi-fashion-cmo",
    "city": "Jeddah"
  },
  {
    "first_name": "Faisal",
    "last_name": "Al-Zaabi",
    "email": "faisal.alzaabi@nexaretail.ae",
    "company": "Nexa Retail Solutions",
    "designation": "Chief Executive Officer",
    "industry": "Retail",
    "country": "UAE",
    "phone": "+971561567890",
    "website": "https://www.nexaretail.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/faisal-alzaabi-nexa",
    "city": "Sharjah"
  },
  {
    "first_name": "Hana",
    "last_name": "Qasimi",
    "email": "hana.qasimi@vervemodasa.com",
    "company": "Verve Moda SA",
    "designation": "Marketing Director",
    "industry": "Fashion",
    "country": "Saudi Arabia",
    "phone": "+966501234890",
    "website": "https://www.vervemodasa.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/hana-qasimi-verve",
    "city": "Riyadh"
  },
  {
    "first_name": "Omar",
    "last_name": "Shehab",
    "email": "omar.shehab@cartexpress.ae",
    "company": "CartExpress UAE",
    "designation": "CMO",
    "industry": "E-commerce",
    "country": "UAE",
    "phone": "+971509876543",
    "website": "https://www.cartexpress.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/omar-shehab-ecommerce",
    "city": "Dubai"
  },
  {
    "first_name": "Reem",
    "last_name": "Al-Suwaidi",
    "email": "reem.alsuwaidi@luxelane.ae",
    "company": "LuxeLane Fashion House",
    "designation": "Chief Executive Officer",
    "industry": "Fashion Retail",
    "country": "UAE",
    "phone": "+971542678901",
    "website": "https://www.luxelane.ae",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/reem-alsuwaidi-luxelane",
    "city": "Dubai"
  },
  {
    "first_name": "Yousef",
    "last_name": "Al-Harbi",
    "email": "yousef.alharbi@peakstylegroup.sa",
    "company": "Peak Style Group KSA",
    "designation": "Marketing Director",
    "industry": "Fashion E-commerce",
    "country": "Saudi Arabia",
    "phone": "+966509871234",
    "website": "https://www.peakstylegroup.sa",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/yousef-alharbi-peakstyle",
    "city": "Jeddah"
  },
  {
    "first_name": "Sarah",
    "last_name": "Mitchell",
    "email": "s.mitchell@google.com",
    "company": "Google",
    "designation": "Chief Marketing Officer",
    "industry": "Retail",
    "country": "United States",
    "phone": "+1 650-253-0000",
    "website": "http://www.google.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Mountain View"
  },
  {
    "first_name": "Neil",
    "last_name": "Lindsay",
    "email": "nlindsay@amazon.com",
    "company": "Amazon",
    "designation": "Senior Vice President, Worldwide Marketing",
    "industry": "Retail",
    "country": "United States",
    "phone": "+1 206-266-1000",
    "website": "http://www.amazon.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Seattle"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Maheshwari",
    "email": "rajesh.maheshwari@adityabirla.com",
    "company": "Aditya Birla Group",
    "designation": "Chief Marketing Officer - Retail",
    "industry": "Retail",
    "country": "India",
    "phone": "+91 22 2665 5160",
    "website": "http://www.adityabirla.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Mumbai"
  },
  {
    "first_name": "Greg",
    "last_name": "Joswiak",
    "email": "gjoswiak@apple.com",
    "company": "Apple Inc.",
    "designation": "Senior Vice President of Worldwide Marketing",
    "industry": "Retail",
    "country": "United States",
    "phone": "+1 408-996-1010",
    "website": "http://www.apple.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Cupertino"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Nambiar",
    "email": "rajesh.nambiar@accenture.com",
    "company": "Accenture",
    "designation": "Managing Director - Retail, India",
    "industry": "Retail",
    "country": "India",
    "phone": "+353 1 646 2000",
    "website": "http://www.accenture.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Bengaluru"
  },
  {
    "first_name": "Shantanu",
    "last_name": "Narayen",
    "email": "shantanu.narayen@adobe.com",
    "company": "adobe",
    "designation": "CEO",
    "industry": "Retail",
    "country": "United States",
    "phone": "+1 408-536-6000",
    "website": "http://www.adobe.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "San Jose"
  },
  {
    "first_name": "Yamini",
    "last_name": "Rangan",
    "email": "yrangan@hubspot.com",
    "company": "Hubspot, Inc.",
    "designation": "Chief Executive Officer",
    "industry": "Retail",
    "country": "United States",
    "phone": "+1 888-482-7768",
    "website": "http://www.hubspot.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Cambridge"
  },
  {
    "first_name": "Rachel",
    "last_name": "Morrison",
    "email": "rachel.morrison@meta.com",
    "company": "<test lead: dummy data for company name>",
    "designation": "Chief Marketing Officer",
    "industry": "Retail",
    "country": "United States",
    "phone": "+1 650-543-4800",
    "website": "http://www.meta.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Menlo Park"
  },
  {
    "first_name": "Lorraine",
    "last_name": "Twohill",
    "email": "ltwohill@google.com",
    "company": "Google",
    "designation": "Chief Marketing Officer",
    "industry": "Retail",
    "country": "United States",
    "phone": "+1 650-253-0000",
    "website": "http://www.google.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Mountain View"
  },
  {
    "first_name": "Andrew",
    "last_name": "Jassy",
    "email": "ajassy@amazon.com",
    "company": "Amazon",
    "designation": "Chief Executive Officer",
    "industry": "Retail",
    "country": "United States",
    "phone": "+1 206-266-1000",
    "website": "http://www.amazon.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Seattle"
  },
  {
    "first_name": "Shantanu",
    "last_name": "Narayen",
    "email": "snarayen@adobe.com",
    "company": "adobe",
    "designation": "CEO",
    "industry": "Retail",
    "country": "United States",
    "phone": "+1 408-536-6000",
    "website": "http://www.adobe.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "San Jose"
  },
  {
    "first_name": "Rakesh",
    "last_name": "Sharma",
    "email": "rakesh.sharma@adityabirla.com",
    "company": "Aditya Birla Group",
    "designation": "Chief Marketing Officer",
    "industry": "Retail",
    "country": "India",
    "phone": "+91 22 2665 5160",
    "website": "http://www.adityabirla.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Mumbai"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Kumar",
    "email": "rajesh.kumar@accenture.com",
    "company": "Accenture",
    "designation": "Marketing Director - Retail",
    "industry": "Retail",
    "country": "India",
    "phone": "+353 1 646 2000",
    "website": "http://www.accenture.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Bengaluru"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Menon",
    "email": "rajesh.menon@accenture.com",
    "company": "Accenture",
    "designation": "Marketing Director - Retail India",
    "industry": "Retail",
    "country": "India",
    "phone": "+353 1 646 2000",
    "website": "http://www.accenture.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Bengaluru"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Dahiya",
    "email": "rajesh.dahiya@adityabirla.com",
    "company": "Aditya Birla Group",
    "designation": "Chief Marketing Officer",
    "industry": "Retail",
    "country": "India",
    "phone": "+91 22 2665 5160",
    "website": "http://www.adityabirla.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Mumbai"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Krishnan",
    "email": "rajesh.krishnan@accenture.com",
    "company": "Accenture",
    "designation": "Marketing Director - Retail",
    "industry": "Retail",
    "country": "India",
    "phone": "+353 1 646 2000",
    "website": "http://www.accenture.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Bengaluru"
  },
  {
    "first_name": "Michael",
    "last_name": "Garber",
    "email": "m.garber@advancedpcb.com",
    "company": "Advanced Circuits",
    "designation": "CEO",
    "industry": "Manufacturer",
    "country": "United States",
    "phone": "(800) 979-4722",
    "website": "https://www.advancedpcb.com/en-us/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Aurora"
  },
  {
    "first_name": "Robert",
    "last_name": "Hendricks",
    "email": "r.hendricks@indian-industries.com",
    "company": "Indian Industries",
    "designation": "Owner",
    "industry": "Manufacturer",
    "country": "United States",
    "phone": "(817) 265-6731",
    "website": "http://www.indian-industries.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Arlington"
  },
  {
    "first_name": "James",
    "last_name": "Whitfield",
    "email": "j.whitfield@aapcb.com",
    "company": "Summit Interconnect",
    "designation": "Managing Director",
    "industry": "Electronics manufacturer",
    "country": "United States",
    "phone": "(303) 307-9900",
    "website": "http://www.aapcb.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Aurora"
  },
  {
    "first_name": "Sofia",
    "last_name": "Martinez",
    "email": "sofia@indiasfactory.com",
    "company": "Indias Factory LLC",
    "designation": "Founder",
    "industry": "Interior Decorator",
    "country": "Unknown",
    "phone": "(303) 589-8027",
    "website": "http://indiasfactory.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": ""
  },
  {
    "first_name": "Daniel",
    "last_name": "Kowalski",
    "email": "d.kowalski@gptindustries.com",
    "company": "GPT Industries Denver",
    "designation": "Sales Director",
    "industry": "Gasket manufacturer",
    "country": "United States",
    "phone": "(303) 988-1242",
    "website": "https://www.gptindustries.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Wheat Ridge"
  },
  {
    "first_name": "Thomas",
    "last_name": "Davis",
    "email": "t.davis@davis-manufacturing.com",
    "company": "Davis Manufacturing Company",
    "designation": "Owner",
    "industry": "Manufacturer",
    "country": "United States",
    "phone": "(303) 762-0550",
    "website": "https://davis-manufacturing.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Wheat Ridge"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Patel",
    "email": "rajesh.patel@yamunaindustry.com",
    "company": "Yamuna Industries",
    "designation": "Director",
    "industry": "Bearing supplier",
    "country": "India",
    "phone": "+91 96381 34351",
    "website": "http://www.yamunaindustry.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Surendranagar"
  },
  {
    "first_name": "Mihir",
    "last_name": "Shah",
    "email": "mihir.shah@difdindustries.com",
    "company": "DIFD Industries Pvt Ltd",
    "designation": "Co-Founder",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "",
    "website": "http://www.difdindustries.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Sedla"
  },
  {
    "first_name": "Amit",
    "last_name": "Desai",
    "email": "amit.desai@gidonline.com",
    "company": "Gujarat Industries Directory",
    "designation": "CEO",
    "industry": "Information and technology services",
    "country": "India",
    "phone": "+91 79 2660 1823",
    "website": "http://gidonline.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Nilesh",
    "last_name": "Joshi",
    "email": "nilesh.joshi@jrindustries.co.in",
    "company": "JR INDUSTRIES - Industrial Valves Manufacturers",
    "designation": "Managing Director",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 93777 22025",
    "website": "http://www.jrindustries.co.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Patel",
    "email": "rajesh.patel@gujaratindustrialchemicals.com",
    "company": "Gujarat Industrial Chemicals Co Pvt LTD",
    "designation": "Managing Director",
    "industry": "Chemical manufacturer",
    "country": "India",
    "phone": "",
    "website": "",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Sokhada"
  },
  {
    "first_name": "Jigar",
    "last_name": "Shah",
    "email": "jigar.shah@jkindus.com",
    "company": "J. K. Industries",
    "designation": "Owner",
    "industry": "Machining manufacturer",
    "country": "India",
    "phone": "+91 99789 20441",
    "website": "https://www.jkindus.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Kalol"
  },
  {
    "first_name": "Mahesh",
    "last_name": "Desai",
    "email": "mahesh.desai@gujaratindustries.co.in",
    "company": "GUJARAT INDUSTRIES",
    "designation": "Director",
    "industry": "Machinery parts manufacturer",
    "country": "India",
    "phone": "+91 98790 04436",
    "website": "http://www.gujaratindustries.co.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Moraiya, Changodar"
  },
  {
    "first_name": "Nilesh",
    "last_name": "Patel",
    "email": "nilesh.patel@gujratindustries.com",
    "company": "Gujarat industries",
    "designation": "Founder",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 99744 50507",
    "website": "http://www.gujratindustries.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Sihor, Ghanghali"
  },
  {
    "first_name": "Dinesh",
    "last_name": "Chauhan",
    "email": "dinesh.chauhan@chamundaindustries.in",
    "company": "Chamunda industries - Pharma Machinery Manufacturer and Supplier in Ahmedabad, Gujarat, India",
    "designation": "CEO",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 98790 26768",
    "website": "https://chamundaindustries.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Kujad, Bakrol Bujrang"
  },
  {
    "first_name": "Suresh",
    "last_name": "Mehta",
    "email": "suresh.mehta@kcil.co.in",
    "company": "Kutch Chemicals Industries Limited",
    "designation": "Managing Director",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 265 239 7013",
    "website": "http://www.kcil.co.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara"
  },
  {
    "first_name": "Amit",
    "last_name": "Trivedi",
    "email": "amit.trivedi@atlantischemical.com",
    "company": "Atlantis Chemicals",
    "designation": "Director",
    "industry": "Chemical manufacturer",
    "country": "India",
    "phone": "+91 98796 41393",
    "website": "http://www.atlantischemical.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": ""
  },
  {
    "first_name": "Bhavesh",
    "last_name": "Modi",
    "email": "bhavesh.modi@gujaratchempharma.com",
    "company": "GUJARAT CHEMICAL AND PHARMACEUTICAL",
    "designation": "Owner",
    "industry": "Chemical wholesaler",
    "country": "India",
    "phone": "+91 90233 90780",
    "website": "https://gujaratchempharma.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara, Fajalpur"
  },
  {
    "first_name": "Harshad",
    "last_name": "Joshi",
    "email": "harshad.joshi@gcacpl.co.in",
    "company": "Gujarat Credo Alumina Chemicals Ltd. (GCACL)",
    "designation": "CEO",
    "industry": "Chemical manufacturer",
    "country": "India",
    "phone": "",
    "website": "http://www.gcacpl.co.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Mundra"
  },
  {
    "first_name": "Kalpesh",
    "last_name": "Baria",
    "email": "kalpesh.baria@calyumchemicals.com",
    "company": "CALYUM CHEMICALS INDUSTRIES",
    "designation": "Founder",
    "industry": "Chemical manufacturer",
    "country": "India",
    "phone": "+91 94085 88035",
    "website": "",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Sonarada, Sonarda"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Patel",
    "email": "rajesh.patel@futuraengineering.in",
    "company": "Futura Engineering Private Limited",
    "designation": "Founder",
    "industry": "Mechanical engineer",
    "country": "India",
    "phone": "+91 97277 63912",
    "website": "http://futuraengineering.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Kalol, Chhatral"
  },
  {
    "first_name": "Dhaval",
    "last_name": "Shah",
    "email": "dhaval@dhavalengg.com",
    "company": "Dhaval Engineering Company",
    "designation": "Owner",
    "industry": "Mechanical contractor",
    "country": "India",
    "phone": "+91 265 232 6233",
    "website": "https://dhavalengg.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara"
  },
  {
    "first_name": "Suresh",
    "last_name": "Mehta",
    "email": "suresh.mehta@gujaratengineeringworks.com",
    "company": "Gujarat Engineering Works",
    "designation": "Managing Director",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 98983 85039",
    "website": "",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara"
  },
  {
    "first_name": "Arvind",
    "last_name": "Desai",
    "email": "arvind.desai@iecindia.co.in",
    "company": "INDIAN ENGINEERING COMPANY",
    "designation": "Director",
    "industry": "Engineering consultant",
    "country": "India",
    "phone": "+91 98240 29088",
    "website": "http://www.iecindia.co.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara"
  },
  {
    "first_name": "Nilesh",
    "last_name": "Panchal",
    "email": "nilesh@denplex.co",
    "company": "Denplex Engineering Company",
    "designation": "Founder",
    "industry": "Toolroom",
    "country": "India",
    "phone": "+91 90333 38999",
    "website": "http://www.denplex.co/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Santej, Gandhinagar"
  },
  {
    "first_name": "Mahesh",
    "last_name": "Parmar",
    "email": "mahesh.parmar@gemi-gujarat.com",
    "company": "GEMI - Gujarat Equipment Manufacturing Industries",
    "designation": "Managing Director",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "",
    "website": "https://www.indiamart.com/gemi-gujarat-equipments/aboutus.html",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Ravi",
    "last_name": "Banka",
    "email": "ravi@ravimachines.com",
    "company": "Banka Machine",
    "designation": "CEO",
    "industry": "Industrial equipment supplier",
    "country": "India",
    "phone": "+91 93770 93780",
    "website": "https://www.ravimachines.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Rajkot"
  },
  {
    "first_name": "Hitesh",
    "last_name": "Ramani",
    "email": "hitesh@premierlathe.co.in",
    "company": "PREMIER LATHE MANUFACTURING COMPANY",
    "designation": "Owner",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 98794 18004",
    "website": "https://premierlathe.co.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Rajkot"
  },
  {
    "first_name": "Shamji",
    "last_name": "Kothari",
    "email": "shamji@metalcastparts.com",
    "company": "Sham Industries",
    "designation": "Founder",
    "industry": "Dairy farm equipment supplier",
    "country": "India",
    "phone": "+91 99256 85858",
    "website": "http://metalcastparts.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Vivek",
    "last_name": "Nair",
    "email": "vivek.nair@godrejenterprises.com",
    "company": "Godrej and Boyce Manufacturing Company Limited",
    "designation": "Sales Director",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 79 6606 0606",
    "website": "https://www.godrejenterprises.com/intralogistics/material-handling-equipment",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Rajiv",
    "last_name": "Sharma",
    "email": "rajiv.sharma@machineindia.com",
    "company": "Machine India Company",
    "designation": "Managing Director",
    "industry": "Machining manufacturer",
    "country": "India",
    "phone": "+91 172 258 5013",
    "website": "",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Panchkula"
  },
  {
    "first_name": "Brian",
    "last_name": "Kowalski",
    "email": "brian.kowalski@flexmachinetools.com",
    "company": "Flex Machine Tools",
    "designation": "CEO",
    "industry": "Manufacturer",
    "country": "United States",
    "phone": "(937) 210-9541",
    "website": "https://www.flexmachinetools.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Wapakoneta"
  },
  {
    "first_name": "David",
    "last_name": "Hemming",
    "email": "david.hemming@milltronics.com",
    "company": "Milltronics",
    "designation": "Sales Director",
    "industry": "Manufacturer",
    "country": "United States",
    "phone": "(952) 442-1410",
    "website": "https://milltronics.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Indianapolis"
  },
  {
    "first_name": "Jason",
    "last_name": "Tucker",
    "email": "jason.tucker@bigmachinedistillery.com",
    "company": "Big Machine Brewery & Distillery",
    "designation": "Founder",
    "industry": "Distillery",
    "country": "United States",
    "phone": "(615) 345-4539",
    "website": "https://www.bigmachinedistillery.com/pages/broadway",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Nashville"
  },
  {
    "first_name": "Mark",
    "last_name": "Patterson",
    "email": "mark.patterson@pearlequipment.com",
    "company": "Pearl Equipment Co.",
    "designation": "Owner",
    "industry": "Industrial equipment supplier",
    "country": "United States",
    "phone": "(615) 383-8703",
    "website": "https://pearlequipment.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Nashville"
  },
  {
    "first_name": "Sarthak",
    "last_name": "Patel",
    "email": "sarthak.patel@sarthaktubemill.com",
    "company": "Sarthak Industries - #1 Tube Mill Machine Manufacturer in India",
    "designation": "Founder",
    "industry": "Machining manufacturer",
    "country": "India",
    "phone": "+91 75748 79515",
    "website": "https://www.sarthaktubemill.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Bakrol Bujrang"
  },
  {
    "first_name": "Kusum",
    "last_name": "Shah",
    "email": "kusum.shah@kusumeng.com",
    "company": "Kusum Engineering Works | Girth Gear | Girth Gear Manufacturer | Girth Gear For Sugar Mill | Sugar Mill Spares",
    "designation": "Managing Director",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 98790 17673",
    "website": "http://kusumeng.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Hitesh",
    "last_name": "Desai",
    "email": "hitesh.desai@gujaratminerals.com",
    "company": "Gujarat Minerals Industries",
    "designation": "Director",
    "industry": "Pharmaceutical company",
    "country": "India",
    "phone": "+91 98253 20194",
    "website": "",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara, Raman Gamdi"
  },
  {
    "first_name": "Nilesh",
    "last_name": "Mehta",
    "email": "nilesh.mehta@gujindpro.com",
    "company": "Gujarat Industrial Products, Industrial fabricator & Manufacturer of MS Storage tanks & Canopies",
    "designation": "Owner",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 93273 48430",
    "website": "https://www.gujindpro.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara"
  },
  {
    "first_name": "Amitbhai",
    "last_name": "Patel",
    "email": "amitbhai.patel@apollo.co.in",
    "company": "Gujarat Apollo Industries Limited",
    "designation": "CEO",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 79 2644 4598",
    "website": "http://apollo.co.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Patel",
    "email": "rajesh.patel@gujaratlathe.com",
    "company": "Gujarat Lathe Manufacturing Company Private Limited",
    "designation": "Managing Director",
    "industry": "Machining manufacturer",
    "country": "India",
    "phone": "+91 2827 252 394",
    "website": "http://www.gujaratlathe.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Shapar"
  },
  {
    "first_name": "Sanjay",
    "last_name": "Shah",
    "email": "sanjay.shah@skyconsultancy.in",
    "company": "SKY consultancy & Engineering Solution",
    "designation": "Founder",
    "industry": "Consultant",
    "country": "India",
    "phone": "+91 94266 99019",
    "website": "http://www.skyconsultancy.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Dinesh",
    "last_name": "Trivedi",
    "email": "dinesh.trivedi@tridevconsultant.com",
    "company": "TRIDEV Industrial (Subsidy) Consultancy",
    "designation": "Director",
    "industry": "Consultant",
    "country": "India",
    "phone": "+91 98982 81360",
    "website": "https://tridevconsultant.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Mehsana(GUJARAT), Mehsana"
  },
  {
    "first_name": "Mihir",
    "last_name": "Desai",
    "email": "mihir.desai@sharanamconsultants.com",
    "company": "𝗦𝗵𝗮𝗿𝗮𝗻𝗮𝗺 𝗖𝗶𝘃𝗶𝗹 𝗖𝗼𝗻𝘀𝘂𝗹𝘁𝗮𝗻𝗰𝘆 | 𝗣𝗿𝗼𝗷𝗲𝗰𝘁 𝗠𝗮𝗻𝗮𝗴𝗲𝗺𝗲𝗻𝘁 𝗖𝗼𝗻𝘀𝘂𝗹𝘁𝗮𝗻𝗰𝘆 𝗙𝗼𝗿 𝗥𝗲𝘀𝗶𝗱𝗲𝗻𝘁𝗶𝗮𝗹, 𝗖𝗼𝗺𝗺𝗲𝗿𝗰𝗶𝗮𝗹 , 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝗶𝗮𝗹 𝗔𝗻𝗱 𝗜𝗻𝘁𝗲𝗿𝗶𝗼𝗿 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀",
    "designation": "Founder",
    "industry": "Engineering consultant",
    "country": "India",
    "phone": "",
    "website": "https://sharanamconsultants.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Nilesh",
    "last_name": "Mehta",
    "email": "nilesh.mehta@divineleansolutions.com",
    "company": "Divine Industrial Consultants",
    "designation": "CEO",
    "industry": "Business management consultant",
    "country": "India",
    "phone": "+91 95865 27037",
    "website": "http://www.divineleansolutions.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Hardik",
    "last_name": "Joshi",
    "email": "hardik.joshi@brilliantapproach.com",
    "company": "Brilliant Approach Private Limited",
    "designation": "Co-Founder",
    "industry": "Engineering consultant",
    "country": "India",
    "phone": "+91 92760 09000",
    "website": "http://brilliantapproach.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Kumar",
    "last_name": "Mangalam",
    "email": "kumar.mangalam@adityabirla.com",
    "company": "Aditya Birla Group",
    "designation": "Chairman",
    "industry": "manufacturing",
    "country": "India",
    "phone": "+91 22 2665 5160",
    "website": "http://www.adityabirla.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Mumbai"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Patel",
    "email": "rajesh.patel@gujratindustries.com",
    "company": "Gujarat industries",
    "designation": "Owner",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 99744 50507",
    "website": "http://www.gujratindustries.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Sihor, Ghanghali"
  },
  {
    "first_name": "Amit",
    "last_name": "Shah",
    "email": "amit.shah@apollo.co.in",
    "company": "Gujarat Apollo Industries Limited",
    "designation": "Managing Director",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 79 2644 4598",
    "website": "http://apollo.co.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Dinesh",
    "last_name": "Parmar",
    "email": "dinesh.parmar@gujaratmineralsindustries.com",
    "company": "Gujarat Minerals Industries",
    "designation": "Founder",
    "industry": "Pharmaceutical company",
    "country": "India",
    "phone": "+91 98253 20194",
    "website": "",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara, Raman Gamdi"
  },
  {
    "first_name": "Suresh",
    "last_name": "Mehta",
    "email": "suresh.mehta@gujaratlathe.com",
    "company": "Gujarat Lathe Manufacturing Company Private Limited",
    "designation": "Director",
    "industry": "Machining manufacturer",
    "country": "India",
    "phone": "+91 2827 252 394",
    "website": "http://www.gujaratlathe.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Shapar"
  },
  {
    "first_name": "Kamlesh",
    "last_name": "Desai",
    "email": "kamlesh.desai@gemi-gujarat.com",
    "company": "GEMI - Gujarat Equipment Manufacturing Industries",
    "designation": "CEO",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "",
    "website": "https://www.indiamart.com/gemi-gujarat-equipments/aboutus.html",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Nilesh",
    "last_name": "Trivedi",
    "email": "nilesh.trivedi@gujindpro.com",
    "company": "Gujarat Industrial Products, Industrial fabricator & Manufacturer of MS Storage tanks & Canopies",
    "designation": "Owner",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 93273 48430",
    "website": "https://www.gujindpro.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara"
  },
  {
    "first_name": "Bhavesh",
    "last_name": "Modi",
    "email": "bhavesh.modi@gujaratindustries.co.in",
    "company": "GUJARAT INDUSTRIES",
    "designation": "Managing Director",
    "industry": "Machinery parts manufacturer",
    "country": "India",
    "phone": "+91 98790 04436",
    "website": "http://www.gujaratindustries.co.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Moraiya, Changodar"
  },
  {
    "first_name": "Jayesh",
    "last_name": "Kapadia",
    "email": "jayesh.kapadia@jkindus.com",
    "company": "J. K. Industries",
    "designation": "Founder",
    "industry": "Machining manufacturer",
    "country": "India",
    "phone": "+91 99789 20441",
    "website": "https://www.jkindus.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Kalol"
  },
  {
    "first_name": "Chandrakant",
    "last_name": "Prajapati",
    "email": "chandrakant.prajapati@chamundaindustries.in",
    "company": "Chamunda industries - Pharma Machinery Manufacturer and Supplier in Ahmedabad, Gujarat, India",
    "designation": "Director",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 98790 26768",
    "website": "https://chamundaindustries.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Kujad, Bakrol Bujrang"
  },
  {
    "first_name": "Harshad",
    "last_name": "Solanki",
    "email": "harshad.solanki@gujaratindustrialchemicals.com",
    "company": "Gujarat Industrial Chemicals Co Pvt LTD",
    "designation": "CEO",
    "industry": "Chemical manufacturer",
    "country": "India",
    "phone": "",
    "website": "",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Sokhada"
  },
  {
    "first_name": "Shamji",
    "last_name": "Patel",
    "email": "shamji.patel@metalcastparts.com",
    "company": "Sham Industries",
    "designation": "Owner",
    "industry": "Dairy farm equipment supplier",
    "country": "India",
    "phone": "+91 99256 85858",
    "website": "http://metalcastparts.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Mihir",
    "last_name": "Shah",
    "email": "mihir.shah@mihirlathe.in",
    "company": "Mihir Machine Tools (Gujarat) Pvt. Ltd. - Lathe Machine",
    "designation": "Founder",
    "industry": "Machine shop",
    "country": "India",
    "phone": "+91 98242 13207",
    "website": "http://www.mihirlathe.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Shapar"
  },
  {
    "first_name": "Dhaval",
    "last_name": "Desai",
    "email": "dhaval.desai@dhavalengg.com",
    "company": "Dhaval Engineering Company",
    "designation": "Managing Director",
    "industry": "Mechanical contractor",
    "country": "India",
    "phone": "+91 265 232 6233",
    "website": "https://dhavalengg.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Mehta",
    "email": "rajesh.mehta@futuraengineering.in",
    "company": "Futura Engineering Private Limited",
    "designation": "Director",
    "industry": "Mechanical engineer",
    "country": "India",
    "phone": "+91 97277 63912",
    "website": "http://futuraengineering.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Kalol, Chhatral"
  },
  {
    "first_name": "Suresh",
    "last_name": "Prajapati",
    "email": "suresh.prajapati@gujaratengineeringworks.com",
    "company": "Gujarat Engineering Works",
    "designation": "Owner",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 98983 85039",
    "website": "",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara"
  },
  {
    "first_name": "Nitin",
    "last_name": "Joshi",
    "email": "nitin.joshi@iecindia.co.in",
    "company": "INDIAN ENGINEERING COMPANY",
    "designation": "CEO",
    "industry": "Engineering consultant",
    "country": "India",
    "phone": "+91 98240 29088",
    "website": "http://www.iecindia.co.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara"
  },
  {
    "first_name": "Denish",
    "last_name": "Panchal",
    "email": "denish.panchal@denplex.co",
    "company": "Denplex Engineering Company",
    "designation": "Founder",
    "industry": "Toolroom",
    "country": "India",
    "phone": "+91 90333 38999",
    "website": "http://www.denplex.co/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Santej, Gandhinagar"
  },
  {
    "first_name": "Arvind",
    "last_name": "Thakkar",
    "email": "arvind.thakkar@ariseindustrialpark.com",
    "company": "Arise Industrial Park - Industrial Park in Gujarat | Industrial Park Investment",
    "designation": "Managing Director",
    "industry": "Construction company",
    "country": "India",
    "phone": "+91 72028 82288",
    "website": "",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Chhatral"
  },
  {
    "first_name": "Anil",
    "last_name": "Chauhan",
    "email": "anil.chauhan@gipcl.com",
    "company": "Gujarat Industries Power Co. Ltd.",
    "designation": "Director",
    "industry": "Corporate office",
    "country": "India",
    "phone": "",
    "website": "https://www.gipcl.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Bhuj, Mirjapar Part"
  },
  {
    "first_name": "Manish",
    "last_name": "Modi",
    "email": "manish.modi@menit.in",
    "company": "Gujarat Industries",
    "designation": "Co-Founder",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 99258 11202",
    "website": "http://www.menit.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Michael",
    "last_name": "Huff",
    "email": "michael.huff@huffinternationalfoods.com",
    "company": "Huff International Foods LLC",
    "designation": "Owner",
    "industry": "Wholesale grocer",
    "country": "United States",
    "phone": "(877) 264-8335",
    "website": "https://huffinternationalfoods.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Los Angeles"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Patel",
    "email": "rajesh.patel@gujarattools.com",
    "company": "Gujarat Industrial Tools Company",
    "designation": "Managing Director",
    "industry": "Industrial equipment supplier",
    "country": "India",
    "phone": "+91 88660 24869",
    "website": "https://www.gujarattools.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Surat, Sachin INA"
  },
  {
    "first_name": "Mehul",
    "last_name": "Shah",
    "email": "mehul.shah@metrochemgroup.com",
    "company": "METRO CHEM INDUSTRIES",
    "designation": "CEO",
    "industry": "Chemical manufacturer",
    "country": "India",
    "phone": "+91 70452 69159",
    "website": "http://www.metrochemgroup.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Dinesh",
    "last_name": "Desai",
    "email": "dinesh.desai@icidyes.com",
    "company": "Indian Chemical Industries",
    "designation": "Director",
    "industry": "Chemical manufacturer",
    "country": "India",
    "phone": "+91 79 2274 0352",
    "website": "http://www.icidyes.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Hardik",
    "last_name": "Trivedi",
    "email": "hardik.trivedi@gcacpl.co.in",
    "company": "Gujarat Credo Alumina Chemicals Ltd. (GCACL)",
    "designation": "Managing Director",
    "industry": "Chemical manufacturer",
    "country": "India",
    "phone": "",
    "website": "http://www.gcacpl.co.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Mundra"
  },
  {
    "first_name": "Bhavesh",
    "last_name": "Chauhan",
    "email": "bhavesh.chauhan@calyumchemicals.com",
    "company": "CALYUM CHEMICALS INDUSTRIES",
    "designation": "Founder",
    "industry": "Chemical manufacturer",
    "country": "India",
    "phone": "+91 94085 88035",
    "website": "",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Sonarada, Sonarda"
  },
  {
    "first_name": "Suresh",
    "last_name": "Kothari",
    "email": "suresh.kothari@kcil.co.in",
    "company": "Kutch Chemicals Industries Limited",
    "designation": "CEO",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 265 239 7013",
    "website": "http://www.kcil.co.in/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Vadodara"
  },
  {
    "first_name": "Jayesh",
    "last_name": "Mistry",
    "email": "jayesh.mistry@jsmindustry.com",
    "company": "Jay Shree Mahalaxmi industries Pharma Equipment Manufacturer",
    "designation": "Founder",
    "industry": "Manufacturer",
    "country": "India",
    "phone": "+91 90167 69969",
    "website": "http://www.jsmindustry.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Ravi",
    "last_name": "Banka",
    "email": "ravi.banka@ravimachines.com",
    "company": "Banka Machine",
    "designation": "Owner",
    "industry": "Industrial equipment supplier",
    "country": "India",
    "phone": "+91 93770 93780",
    "website": "https://www.ravimachines.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Rajkot"
  },
  {
    "first_name": "Amit",
    "last_name": "Parikh",
    "email": "amit.parikh@gujaratmachinery.com",
    "company": "GUJARAT MACHINERY PRIVATE LIMITED",
    "designation": "Managing Director",
    "industry": "Corporate office",
    "country": "India",
    "phone": "",
    "website": "http://www.gujaratmachinery.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad, Miroli"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Patel",
    "email": "rajesh.patel@brilliantapproach.com",
    "company": "Brilliant Approach Private Limited",
    "designation": "Founder",
    "industry": "Engineering consultant",
    "country": "India",
    "phone": "+91 92760 09000",
    "website": "http://brilliantapproach.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Mahesh",
    "last_name": "Lakhara",
    "email": "mahesh.lakhara@lakharaconsultant.com",
    "company": "LAKHARA M M Consultant (Industrial Subsidy)",
    "designation": "Owner",
    "industry": "Industrial consultant",
    "country": "India",
    "phone": "+91 94293 06376",
    "website": "",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Niral",
    "last_name": "Shah",
    "email": "niral.shah@sharanamconsultants.com",
    "company": "𝗦𝗵𝗮𝗿𝗮𝗻𝗮𝗺 𝗖𝗶𝘃𝗶𝗹 𝗖𝗼𝗻𝘀𝘂𝗹𝘁𝗮𝗻𝗰𝘆 | 𝗣𝗿𝗼𝗷𝗲𝗰𝘁 𝗠𝗮𝗻𝗮𝗴𝗲𝗺𝗲𝗻𝘁 𝗖𝗼𝗻𝘀𝘂𝗹𝘁𝗮𝗻𝗰𝘆 𝗙𝗼𝗿 𝗥𝗲𝘀𝗶𝗱𝗲𝗻𝘁𝗶𝗮𝗹, 𝗖𝗼𝗺𝗺𝗲𝗿𝗰𝗶𝗮𝗹 , 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝗶𝗮𝗹 𝗔𝗻𝗱 𝗜𝗻𝘁𝗲𝗿𝗶𝗼𝗿 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀",
    "designation": "Director",
    "industry": "Engineering consultant",
    "country": "India",
    "phone": "",
    "website": "https://sharanamconsultants.com/",
    "source": "google_maps",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Mehta",
    "email": "rajesh.mehta@adityabirla.com",
    "company": "Aditya Birla Group",
    "designation": "Managing Director - Manufacturing Operations",
    "industry": "manufacturing",
    "country": "India",
    "phone": "+91 22 2665 5160",
    "website": "http://www.adityabirla.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Mumbai"
  },
  {
    "first_name": "Rajiv",
    "last_name": "Sharma",
    "email": "rajiv.sharma@adityabirla.com",
    "company": "Aditya Birla Group",
    "designation": "Managing Director - Manufacturing Operations",
    "industry": "manufacturing",
    "country": "India",
    "phone": "+91 22 2665 5160",
    "website": "http://www.adityabirla.com",
    "source": "apollo",
    "status": "new_enquiry",
    "linkedin_url": "",
    "city": "Mumbai"
  },
  {
    "first_name": "Rajesh",
    "last_name": "Patel",
    "email": "rajesh.patel@shreeramengineering.com",
    "company": "Shree Ram Engineering Works",
    "designation": "Managing Director",
    "industry": "Machine Manufacturing",
    "country": "India",
    "phone": "+919825034712",
    "website": "https://www.shreeramengineering.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/rajesh-patel-shreeramengineering",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Neha",
    "last_name": "Shah",
    "email": "neha.shah@chemnovagujarat.in",
    "company": "ChemNova Industries Pvt. Ltd.",
    "designation": "Founder & CEO",
    "industry": "Chemical Company",
    "country": "India",
    "phone": "+919974123456",
    "website": "https://www.chemnovaindustries.in",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/neha-shah-chemnova",
    "city": "Vadodara"
  },
  {
    "first_name": "Amit",
    "last_name": "Mehta",
    "email": "amit.mehta@supremeinfratech.com",
    "company": "Supreme Infratech Engineers",
    "designation": "Director",
    "industry": "Engineering Company",
    "country": "India",
    "phone": "+919898501234",
    "website": "https://www.supremeinfratech.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/amit-mehta-supremeinfratech",
    "city": "Surat"
  },
  {
    "first_name": "Dhruv",
    "last_name": "Desai",
    "email": "dhruv.desai@deltaautomation.co.in",
    "company": "Delta Automation Systems",
    "designation": "Co-Founder & CTO",
    "industry": "Industrial Manufacturing",
    "country": "India",
    "phone": "+919712045678",
    "website": "https://www.deltaautomation.co.in",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/dhruv-desai-deltaautomation",
    "city": "Rajkot"
  },
  {
    "first_name": "Priya",
    "last_name": "Joshi",
    "email": "priya.joshi@mahavirpolymers.com",
    "company": "Mahavir Polymers & Chemicals",
    "designation": "Owner & CEO",
    "industry": "Chemical Company",
    "country": "India",
    "phone": "+919825567890",
    "website": "https://www.mahavirpolymers.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/priya-joshi-mahavirpolymers",
    "city": "Ankleshwar"
  },
  {
    "first_name": "Suresh",
    "last_name": "Kothari",
    "email": "suresh.kothari@indoconsultancygroup.in",
    "company": "Indo Consultancy Group",
    "designation": "Founder & Industrial Consultant",
    "industry": "Industrial Consultant",
    "country": "India",
    "phone": "+919376112233",
    "website": "https://www.indoconsultancygroup.in",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/suresh-kothari-indoconsultancy",
    "city": "Ahmedabad"
  },
  {
    "first_name": "Kiran",
    "last_name": "Trivedi",
    "email": "kiran.trivedi@swiftmetfab.com",
    "company": "Swift Metal Fabricators Pvt. Ltd.",
    "designation": "Sales Director",
    "industry": "Manufacturing",
    "country": "India",
    "phone": "+919924334455",
    "website": "https://www.swiftmetfab.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/kiran-trivedi-swiftmetfab",
    "city": "Gandhinagar"
  },
  {
    "first_name": "Manish",
    "last_name": "Agrawal",
    "email": "manish.agrawal@precisiongearworks.com",
    "company": "Precision Gear Works India",
    "designation": "Founder & Managing Director",
    "industry": "Machine Manufacturing",
    "country": "India",
    "phone": "+919898223344",
    "website": "https://www.precisiongearworks.com",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/manish-agrawal-precisiongear",
    "city": "Rajkot"
  },
  {
    "first_name": "Sheetal",
    "last_name": "Panchal",
    "email": "sheetal.panchal@aryaindustrialcorp.in",
    "company": "Arya Industrial Corporation",
    "designation": "Director & Co-Founder",
    "industry": "Industrial Company",
    "country": "India",
    "phone": "+919727445566",
    "website": "https://www.aryaindustrialcorp.in",
    "source": "apify",
    "status": "new_enquiry",
    "linkedin_url": "https://linkedin.com/in/sheetal-panchal-aryaindustrial",
    "city": "Bharuch"
  },
  {
    "first_name": "Vivek",
    "last_name": "Nair",
    "email": "vivek.nair@nexgenmanufacturing.co.in",
    "company": "NexGen Manufacturing Solutions",
    "designation": "CMO",
    "industry": "Industrial Manufacturing",
    "country": "India",
    "phone": "+919662556677",
    "website": "https://www.nexgenmanufacturing.co.in",
    "source": "apify",
    "status": "enquiry_qualified",
    "linkedin_url": "https://linkedin.com/in/vivek-nair-nexgenmanufacturing",
    "city": "Surat"
  }
] as const;

  export interface SyncMissingLeadsSummary {
    checked: number;
    inserted: number;
    skipped: number;
  }

  export async function runSyncMissingLeads(): Promise<SyncMissingLeadsSummary> {
    const emailsToSync = MISSING_LEADS.map((l) => l.email).filter(Boolean);
    if (emailsToSync.length === 0) return { checked: 0, inserted: 0, skipped: 0 };

    const existing = await db
      .select({ email: leads.email })
      .from(leads)
      .where(inArray(leads.email, emailsToSync));

    const existingEmails = new Set(existing.map((r) => r.email?.toLowerCase()));

    let inserted = 0;
    let skipped = 0;

    for (const lead of MISSING_LEADS) {
      if (!lead.email || existingEmails.has(lead.email.toLowerCase())) {
        skipped++;
        continue;
      }
      await db.insert(leads).values({
        firstName: lead.first_name || "",
        lastName: lead.last_name || "",
        email: lead.email,
        company: lead.company || null,
        designation: lead.designation || null,
        industry: lead.industry || null,
        country: lead.country || null,
        phone: lead.phone || null,
        website: lead.website || null,
        source: lead.source || "apify",
        status: "new_enquiry",
        linkedInUrl: lead.linkedin_url || null,
        city: lead.city || null,
      });
      inserted++;
    }

    return { checked: MISSING_LEADS.length, inserted, skipped };
  }
  